### ISSUE TITLE
ActiveBook class

### ISSUE THREAD

**Issue by f-rakete** [PrycilaCerqueira/P7_UrbanRead#1]
https://github.com/PrycilaCerqueira/P7_UrbanRead/blob/38d970e1da099dbc6dc8da4493944a1c1901311e/P7_UrbanRead/P7_UrbanRead/ActiveBook.cs#L11-L19

Not too sure what the purpose of this class is? Is it the current book somebody is reading?

also:

Why are fields of the book type called "title" and "cover"?

why is there a person field called wishlist 🙃

I'll assume that this is the book somebody is currently reading, so your Person class could just have a public Book ActiveBook, no?

**Comment by PrycilaCerqueira** [comment]
Yes, it is. This class has the purpose of presenting a Reading Dashboard to each user.
It presents the books they are reading and their progress.
It has the WhisList available for them to edit their book list. 

The person field called wishlist is because I have this field under Person (private List<Book> _WishList);

**Comment by PrycilaCerqueira** [comment]
ä

**Comment by f-rakete** [comment]
ok so if i get that right i think the most sane order would be:

user has a property list of active book
active book class has properties:
Book active book (contains all the book data like title total pages etc)
int currentPAge
enum? readstatus

**Comment by PrycilaCerqueira** [comment]
@f-rakete, thank you! Code adjusted.
The wishlist field is for the user to create their personal list of desired books.
